### ISSUE TITLE
If the height is changed from the outside while the open/close process has never been executed, it will not synchronize.

### ISSUE THREAD

**Issue by makotot** [roginfarrer/react-collapsed#100]
If it is initially open and a change occurs that changes the internal height, react-collapsed will not reflect the change.
After the second time, the height is correctly recognized as normal.

Reproducing URL:
https://stackblitz.com/edit/react-ts-23bci9?file=App.tsx

Pressing the "+1" button does not change the height of the item, so the item is not fully displayed.
If you press the "Toggle" button once, the height will always be updated, with all items displayed.

I'm assuming this behavior is probably a bug, not a specification. But I don't know much about it.
I am not sure if this is the scope of react-collapsed too.

`defaultExpanded` value has no effect.

**Comment by makotot** [comment]
This problem does not seem to occur in React v17 but from v18.
https://stackblitz.com/edit/react-ts-jncunm?file=index.tsx

The same problem does not occur in v18 unless StrictMode is used.

**Comment by roginfarrer** [comment]
Meant to release at v4@next, but couldn't figure out the magic words for semantic-release 🤷🏻. Can you try testing with `react-collapsed@next` @makotot?

**Comment by makotot** [comment]
@roginfarrer Thanks for getting back to me! 
I've tried with v3.8.0 and can confirm the issue has been solved 👍
https://stackblitz.com/edit/react-ts-tunpnu?file=package.json
