### ISSUE TITLE
No longer compatible with React < 18.

### ISSUE THREAD

**Issue by adriantrunzo** [roginfarrer/react-collapsed#117]
# Issue

The [changes introduced in 3.4.0](https://github.com/roginfarrer/react-collapsed/pull/98#issuecomment-1242070536) to add support for the new `useId` hook in React 18 while maintaining backwards compatibility don't seem to be working as intended. At least not when using Webpack. In an app using Create React App v5 (Webpack v5) and React 17, the following compilation error occurs:

```
Failed to compile.

Attempted import error: 'useId' is not exported from 'react' (imported as 'e').
ERROR in ./node_modules/react-collapsed/dist/react-collapsed.esm.js 49:6-13
export 'useId' (imported as 'e') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

webpack compiled with 1 error
No issues found.
```

[Other folks are having the same issue](https://github.com/roginfarrer/react-collapsed/pull/98#issuecomment-1282609722). If you look at the compiled code in the `dist/` directory (react-collapsed.esm.js as downloaded from npm), it starts with `import*as e from"react";` and later calls `y=e.useId`.

# Discussion

I don't know yet why the workaround mentioned in the 3.4.0 pull request works for material-ui and not in this project. Perhaps there is a key difference in how the two projects are distributed.

**Comment by roginfarrer** [comment]
Huh, that's a bummer that it didn't work. Considering that there seems to be another breaking change between v17 and v18, I think it's best to revert the `useId` change on v3, and make v3 compatible with React@<=17. And plan to release a v4 that's compatible with React@^18
