### ISSUE TITLE
New Feature: Introduce Hooks

### ISSUE THREAD

**Issue by hamlim** [roginfarrer/react-collapsed#12]
It would be great to use this component using hooks in React 16.8.1.

Some things that can be done as part of this:

* Internal rewrite using them (maybe?)
* Context based approach (i.e `<Collapse>` becomes a `context.Provider`)
* Expose `useToggle` and `useCollapsible` hooks to get the props for the toggle button and the collapsible container respectively (naming TBD)

**Comment by roginfarrer** [comment]
Resolved in 2.0.0 🎉
