### ISSUE TITLE
Dealing with changing heights

### ISSUE THREAD

**Issue by nickrttn** [roginfarrer/react-collapsed#28]
Hi there.

I'm trying to use `react-collapsed` on an element that has a changing height. Its children are dynamically mounted and only display their content when some data is fetched.

As `react-collapsed` sets a height in `px` on the element it is expanding, some of the content that is loading inside that element is being cut off.

From the docs it isn't immediately apparent to me how I make sure that the height of the element is `auto` _after_ expanding it. Is there any way to do this?

Thanks in advance!

– Nick

**Comment by roginfarrer** [comment]
Hi @nickrttn, can you share a codesandbox or a way to reproduce this? The collapse element should always have its height property stripped after the transition ends (effectively `height: auto`). If the height of the contents change mid-transition, that's a different issue.

**Comment by nickrttn** [comment]
> If the height of the contents change mid-transition, that's a different issue.

This is what was happening. I've solved it by loading all content for expandable elements up front.
