### ISSUE TITLE
[Request] Respond to height updates during animations

### ISSUE THREAD

**Issue by Titozzz** [roginfarrer/react-collapsed#29]
As said in #28, animating and changing height at the same time is not working properly. Do you think this is fixable, or this is by design from that library and cannot change?

Do you need a reproduction? 

Thank you so much for the lib and your time :)

**Comment by Titozzz** [comment]
We improvised something that's working. If the height is updated it will animate another time to the new height.

**Comment by roginfarrer** [comment]
> Do you need a reproduction?

A reproduction would be great! A gif would also work well, since I know timing this can be hard.

**Comment by Titozzz** [comment]
There you go:
[![Edit hardcore-morse-23we0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-morse-23we0?fontsize=14)

Click, let it "load", close it, and reopen it

**Comment by roginfarrer** [comment]
Ah, makes sense! Taking a closer look at the PR now.
