### ISSUE TITLE
Issues with SSR / Next.JS

### ISSUE THREAD

**Issue by ivanji** [roginfarrer/react-collapsed#32]
Thanks for such a helpful project and for keeping it tiny! Love it.

when server side rendering - there's a mismatch between generated ids. It's a pretty common issue. 

```Prop `id` did not match. Server: "react-collapsed-toggle-200" Client: "react-collapsed-toggle-0" ]```

Similar components reset the generated ids. It'd be great if you could provide a way to do so. Thanks!

**Comment by roginfarrer** [comment]
Thanks for the bug report!
Fixed in 2.2.3 🎉
