### ISSUE TITLE
[Question] A way to control the state of the nested collapse component

### ISSUE THREAD

**Issue by mxs17** [roginfarrer/react-collapsed#34]
I need to reset the state of the nested collapse components everytime the outer component is collapsed, i.e. when I open the outer component, all the nested components are always collapsed.

My attempt: https://codesandbox.io/s/busy-morse-v965k
The problem is that _isOpen_ is stale, and I cannot call `toggleOpen` only for blocks that are currently open. 

Is there a workaround for this? If no, I believe this can be solved by adding `close()` (and `open()`) callbacks along with `toggleOpen()`.

**Comment by roginfarrer** [comment]
Could you control the `isOpen` state instead? If you need to be opinionated about the state of the inner blocks, then that sounds like a good reason to control the state.

**Comment by mxs17** [comment]
Thanks for your answer! I probably missed something in my prior attempts with controlling isOpen. Tried to change my example, and it works as expected.
