### ISSUE TITLE
Scroll to top option?

### ISSUE THREAD

**Issue by naazim** [roginfarrer/react-collapsed#35]
When clicked on any element to expand the view, and if the element is at the bottom of the screen, the user has no indication that the view has expanded (I've included part of the blue in the screenshot, but if its not there, you don't realise this change, part of user experience). Providing a scroll to top could help this scenario
![Screenshot 2019-12-19 11 36 20](https://user-images.githubusercontent.com/7804899/71166933-0255dc00-2254-11ea-92dc-c8063b0af2e8.png)
![Screenshot 2019-12-19 11 36 32](https://user-images.githubusercontent.com/7804899/71166934-0255dc00-2254-11ea-9dd4-8d77b3f2313b.png)

**Comment by roginfarrer** [comment]
Hi, thanks for the suggestion! I believe that this kind of behavior does not belong in this library. Forcing the scroll for users can be disorienting. Ideally there should be another indication on the toggle that something is happening (like changing from a "plus" to "minus" icon to indicate the change.)
