### ISSUE TITLE
Toggle button inside collapsible content

### ISSUE THREAD

**Issue by jahirfiquitiva** [roginfarrer/react-collapsed#56]
Hello, I'm trying to have the toggle button inside the content that will be collapsed, but I can't seem to be able to get it to work...

Would you mind helping me to get it to work as intended? ... Here's a quick look at how it should look in both states:

**Expanded**
![Shot 2020-09-26 at 12 32 32](https://user-images.githubusercontent.com/10360816/94346775-7e0b6300-fff4-11ea-9974-55ba21cea2ab.png)

**Collapsed**
![Shot 2020-09-26 at 12 32 43](https://user-images.githubusercontent.com/10360816/94346784-8368ad80-fff4-11ea-9d48-c532c3c9b7b1.png)

Thanks in advance 🙏

**Comment by roginfarrer** [comment]
Can you share a codesandbox of what you have?

**Comment by jahirfiquitiva** [comment]
Nevermind, it was something else
