### ISSUE TITLE
`type=button` discards custom css in Safari

### ISSUE THREAD

**Issue by bebbi** [roginfarrer/react-collapsed#58]
The `type=button` added by `getToggleProps` removes my custom styles such as background-color.
Adding a `[vendor-prefix-]appearance: none` does not change that behavior for me.

Work-arounds: Using a styled `<button>` tag instead to apply `getToggleProps` to doesn't work if there are more buttons inside the collapsible and leads to a dom validation issue about nesting buttons inside buttons.
(Additionally declaring a button tag as `display: flex` does not make it assume full width in Safari even though it should.)

I haven't found out what `type=button` would help with beyond what the aria `role` already solves. Could it be removed from the `getToggleProps`?

**Comment by roginfarrer** [comment]
Can you share a codesandbox or a code snippet recreating the issue? Is the browser adding styles, or are there styles with the `[type=button]` selector on the page?
