### ISSUE TITLE
v3.2 can no longer be imported

### ISSUE THREAD

**Issue by garth** [roginfarrer/react-collapsed#74]
v3.2 can no longer be imported.

```ts
import useCollapse from 'react-collapsed'
```

When building a next.js 11 app you get the following error:

```
 > Build error occurred
 Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/react-collapsed.modern.js" defined in the package config node_modules/react-collapsed/package.json; targets must start with "./"
```

It looks like the wrong dist file is selected, it should probably be `node_modules/react-collapsed/dist/react-collapsed.js`

**Comment by roginfarrer** [comment]
I think this was caused by adding the `"exports"` field to the package.json. I don't think it's needed, so I dropped it. Let me know if you have any issues in 3.2.1!

**Comment by garth** [comment]
That fixed it. Thank you!
