### ISSUE TITLE
Mac OS Safari comes with default CSS

### ISSUE THREAD

**Issue by rafin-rahman** [roginfarrer/react-collapsed#82]
It works fine on Chrome, IOS Safari, iPad Safari, but on mac OS safari has some default CSS styling with a white background and rounded borders. 
<img width="424" alt="footer" src="https://user-images.githubusercontent.com/38799209/159886310-536cd526-d6d9-4beb-9710-4a459d53268d.png">

**Comment by roginfarrer** [comment]
The library only provides the necessary styles for the animation. It's up to the project to handle the presentation of the toggle and the collapse, including resetting vendor styles.
