### ISSUE TITLE
Accordion mode

### ISSUE THREAD

**Issue by VladyslavL** [roginfarrer/react-collapsed#87]
Could you please add an example of making Accordion mode using `useCollapse` in proper way. My example works but without animation as Accordion component re-renders every time `activeItem` state changes. My example: 

```
export const Accordion = ({ data }) => {
	const [activeItem, setActiveItem] = useState(0);

	const onToggle = (index) => {
		const value = index === activeItem ? activeItem : index;
		setActiveItem(value);
	};

	const AccordionItem = ({ item, index, isOpen, onToggle }) => {
		const { getCollapseProps, getToggleProps, isExpanded } = useCollapse({ isExpanded: isOpen });

		return (
			<div className="accordion">
				<header
					className={`accordion-header ${isExpanded ? "active" : ""}`}
					{...getToggleProps({
						onClick: onToggle,
					})}>
					<IconChevronRight />
					<span>{item.heading}</span>
				</header>
				<div {...getCollapseProps()}>
					<main className="accordion-main">
						{item.content.map((content, i) => (
							<AccordionContent content={content} key={i} />
						))}
					</main>
				</div>
				<div className={`img ${isExpanded ? "active" : ""}`}>
					<img src={item.image.url} alt={item.image.alt} />
				</div>
			</div>
		);
	};

	return (
		<>
			{data.map((item, index) => (
				<AccordionItem item={item} index={index} key={index} isOpen={activeItem === index} onToggle={() => onToggle(index)} />
			))}
		</>
	);
};
```

**Comment by roginfarrer** [comment]
I believe the problem your having is that you've defined the AccordionItem within the body of the Accordion component. Whenever the activeItem changes, the Accordion re-renders, causing the AccordionItem to unmount and then mount a new instance. If you move the AccordionItem outside of the Accordion component, that should fix it.

Here's a new demo https://github.com/roginfarrer/react-collapsed/blob/main/src/stories/accordion.stories.tsx

**Comment by VladyslavL** [comment]
@roginfarrer - Works like a charm! Thanks you

**Comment by jovana** [comment]
> I believe the problem you're having is that you've defined the AccordionItem within the body of the Accordion component. Whenever the activeItem changes, the Accordion re-renders, causing the AccordionItem to unmount and then mount a new instance. If you move the AccordionItem outside of the Accordion component, that should fix it.
> 
> Here's a new demo https://github.com/roginfarrer/react-collapsed/blob/main/src/stories/accordion.stories.tsx

Where can I find the source code / example for this? The storiebook gives only a very basic code example, but missing a lot to have a working example.
