### ISSUE TITLE
Is it possible to have 2 icons switch back and forth when expanding or collapsing?

### ISSUE THREAD

**Issue by armsp** [roginfarrer/react-collapsed#93]
Right now we see a button whose text changes.
I was wondering if there is a way to use svg icons or anything else instead of the button. For e.g. ↑ or ↓

**Comment by roginfarrer** [comment]
Yes, the content of the collapse and toggles are completely up to the implementation. Check out the examples within this repo to see the source code of the demos to give you an idea.
