### ISSUE TITLE
inline styling not working

### ISSUE THREAD

**Issue by jutunen** [roginfarrer/react-collapsed#99]
It would be nice to be able to add individual CSS properties dynamically, but this does not work:

    <div style={{position: "absolute"}} {...getCollapseProps()}>

This works, but I can't set CSS properties dynamically:

CSS:

    .myClassName {
        position: absolute;
    }

JS:

    <div className="myClassName" {...getCollapseProps()}>

Anyways, thank you for developing this component!

**Comment by roginfarrer** [comment]
You can, you just need to pass it into getCollapseProps

```tsx 
<div {...getCollapseProps({ style: {position: 'absolute'} })} />
```

It will merge the styles you pass in with the styles required to make the transitions work

**Comment by jutunen** [comment]
Ok, thanks, now I noticed that there is an example in the FAQ section, when I clicked the section open. Maybe you could document this inline styling feature a little better...? ;-)

**Comment by roginfarrer** [comment]
Happy to review a PR to improve the docs! Glad this got resolved.
